version: "3.9"

services:
  db:
    image: postgres:latest
    container_name: donatio-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: donatio
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  donatio_backend:
    image: htayhtaythwe717/donatio:backend_latest
    container_name: donatio-backend
    ports:
      - "8000:8000"
    volumes:
      - ./donatio-django:/app
    environment:
      DEBUG: "1"
      DJANGO_ALLOWED_HOSTS: localhost,127.0.0.1
      GOOGLE_CLIENT_ID: ${GOOGLE_CLIENT_ID}
      GOOGLE_APP_PASSWORD: ${GOOGLE_APP_PASSWORD}
      DATABASE_URL: postgresql://postgres:postgres@db:5432/donatio
    depends_on:
      - db

  donatio_chatbot:
    image: htayhtaythwe717/donatio:chatbot_latest
    container_name: donatio-chatbot
    ports:
      - "8001:8001"
    volumes:
      - ./donatio-chatbot:/app
    environment:
      GROQ_API_KEY: ${GROQ_API_KEY}
      DATABASE_URL: postgresql://postgres:postgres@db:5432/donatio
    depends_on:
      - db

  # donatio_kpay:
  #   build: ./donatio-kpay
  #   container_name: donatio-kpay
  #   ports:
  #     - "8002:8002"
  #   volumes:
  #     - ./donatio-kpay:/app
  #   depends_on: 
  #     - db
      
volumes:
  postgres_data: