name: Docker CI

on:
  push:
    paths:
      - "donatio-django/**"
      - "donatio-chatbot/**"
      - "donatio-kpay/**"
      - "docker-compose.yml"
  pull_request:
    paths:
      - "donatio-django/**"
      - "donatio-chatbot/**"
      - "donatio-kpay/**"
      - "docker-compose.yml"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Django Backend Image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/donatio-backend ./donatio-django

      - name: Build Chatbot Image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/donatio-chatbot ./donatio-chatbot

      # - name: Build KPay Image
      #   run: |
      #     docker build -t ${{ secrets.DOCKER_USERNAME }}/donatio-kpay ./donatio-kpay
      - name: Push All Images to DockerHub
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/donatio-backend
          docker push ${{ secrets.DOCKER_USERNAME }}/donatio-chatbot

        # docker push ${{ secrets.DOCKER_USERNAME }}/donatio-kpay
