name: Docker CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Django Backend Image
        run: |
          docker build \
            --build-arg GOOGLE_APP_PASSWORD="${{ secrets.GOOGLE_APP_PASSWORD }}" \
            --build-arg GOOGLE_CLIENT_ID="${{ secrets.GOOGLE_CLIENT_ID }}" \
            -t ${{ secrets.DOCKER_USERNAME }}/donatio:backend_latest ./donatio-django

      - name: Build Chatbot Image
        run: |
          docker build \
            --build-arg GROQ_API_KEY="${{ secrets.GROQ_API_KEY }}" \
            -t ${{ secrets.DOCKER_USERNAME }}/donatio:chatbot_latest ./donatio-chatbot

      - name: Push All Images to DockerHub
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/donatio:backend_latest
          docker push ${{ secrets.DOCKER_USERNAME }}/donatio:chatbot_latest

      - name: Run Containers with Compose
        env:
          GOOGLE_CLIENT_ID: ${{ secrets.GOOGLE_CLIENT_ID }}
          GOOGLE_APP_PASSWORD: ${{ secrets.GOOGLE_APP_PASSWORD }}
          GROQ_API_KEY: ${{ secrets.GROQ_API_KEY }}
        run: |
          docker compose up -d
